# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /xilinxworks/sysgen/bpm_panda/netlist/ip/bpm_mc/src/ip_catalog/bpm_mc.srcs/sources_1/bd/bpm_mc_bd/ip/bpm_mc_bd_bpm_mc_1_0/bpm_mc_bd_bpm_mc_1_0.xci
# IP: The module: 'bpm_mc_bd_bpm_mc_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /xilinxworks/sysgen/bpm_panda/netlist/ip/bpm_mc/src/ip_catalog/bpm_mc.gen/sources_1/bd/bpm_mc_bd/ip/bpm_mc_bd_bpm_mc_1_0/bpm_mc_c_addsub_v12_0_i0/bpm_mc_c_addsub_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bpm_mc_c_addsub_v12_0_i0 || ORIG_REF_NAME==bpm_mc_c_addsub_v12_0_i0} -quiet] -quiet

# IP: /xilinxworks/sysgen/bpm_panda/netlist/ip/bpm_mc/src/ip_catalog/bpm_mc.gen/sources_1/bd/bpm_mc_bd/ip/bpm_mc_bd_bpm_mc_1_0/bpm_mc_c_addsub_v12_0_i1/bpm_mc_c_addsub_v12_0_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bpm_mc_c_addsub_v12_0_i1 || ORIG_REF_NAME==bpm_mc_c_addsub_v12_0_i1} -quiet] -quiet

# IP: /xilinxworks/sysgen/bpm_panda/netlist/ip/bpm_mc/src/ip_catalog/bpm_mc.gen/sources_1/bd/bpm_mc_bd/ip/bpm_mc_bd_bpm_mc_1_0/bpm_mc_c_addsub_v12_0_i2/bpm_mc_c_addsub_v12_0_i2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bpm_mc_c_addsub_v12_0_i2 || ORIG_REF_NAME==bpm_mc_c_addsub_v12_0_i2} -quiet] -quiet

# IP: /xilinxworks/sysgen/bpm_panda/netlist/ip/bpm_mc/src/ip_catalog/bpm_mc.gen/sources_1/bd/bpm_mc_bd/ip/bpm_mc_bd_bpm_mc_1_0/bpm_mc_c_addsub_v12_0_i3/bpm_mc_c_addsub_v12_0_i3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bpm_mc_c_addsub_v12_0_i3 || ORIG_REF_NAME==bpm_mc_c_addsub_v12_0_i3} -quiet] -quiet

# IP: /xilinxworks/sysgen/bpm_panda/netlist/ip/bpm_mc/src/ip_catalog/bpm_mc.gen/sources_1/bd/bpm_mc_bd/ip/bpm_mc_bd_bpm_mc_1_0/bpm_mc_div_gen_v5_1_i0/bpm_mc_div_gen_v5_1_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bpm_mc_div_gen_v5_1_i0 || ORIG_REF_NAME==bpm_mc_div_gen_v5_1_i0} -quiet] -quiet

# IP: /xilinxworks/sysgen/bpm_panda/netlist/ip/bpm_mc/src/ip_catalog/bpm_mc.gen/sources_1/bd/bpm_mc_bd/ip/bpm_mc_bd_bpm_mc_1_0/bpm_mc_mult_gen_v12_0_i0/bpm_mc_mult_gen_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bpm_mc_mult_gen_v12_0_i0 || ORIG_REF_NAME==bpm_mc_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: /xilinxworks/sysgen/bpm_panda/netlist/ip/bpm_mc/src/ip_catalog/bpm_mc.gen/sources_1/bd/bpm_mc_bd/ip/bpm_mc_bd_bpm_mc_1_0/constrs/bpm_mc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bpm_mc_bd_bpm_mc_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /xilinxworks/sysgen/bpm_panda/netlist/ip/bpm_mc/src/ip_catalog/bpm_mc.srcs/sources_1/bd/bpm_mc_bd/ip/bpm_mc_bd_bpm_mc_1_0/bpm_mc_bd_bpm_mc_1_0.xci
# IP: The module: 'bpm_mc_bd_bpm_mc_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /xilinxworks/sysgen/bpm_panda/netlist/ip/bpm_mc/src/ip_catalog/bpm_mc.gen/sources_1/bd/bpm_mc_bd/ip/bpm_mc_bd_bpm_mc_1_0/bpm_mc_c_addsub_v12_0_i0/bpm_mc_c_addsub_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bpm_mc_c_addsub_v12_0_i0 || ORIG_REF_NAME==bpm_mc_c_addsub_v12_0_i0} -quiet] -quiet

# IP: /xilinxworks/sysgen/bpm_panda/netlist/ip/bpm_mc/src/ip_catalog/bpm_mc.gen/sources_1/bd/bpm_mc_bd/ip/bpm_mc_bd_bpm_mc_1_0/bpm_mc_c_addsub_v12_0_i1/bpm_mc_c_addsub_v12_0_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bpm_mc_c_addsub_v12_0_i1 || ORIG_REF_NAME==bpm_mc_c_addsub_v12_0_i1} -quiet] -quiet

# IP: /xilinxworks/sysgen/bpm_panda/netlist/ip/bpm_mc/src/ip_catalog/bpm_mc.gen/sources_1/bd/bpm_mc_bd/ip/bpm_mc_bd_bpm_mc_1_0/bpm_mc_c_addsub_v12_0_i2/bpm_mc_c_addsub_v12_0_i2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bpm_mc_c_addsub_v12_0_i2 || ORIG_REF_NAME==bpm_mc_c_addsub_v12_0_i2} -quiet] -quiet

# IP: /xilinxworks/sysgen/bpm_panda/netlist/ip/bpm_mc/src/ip_catalog/bpm_mc.gen/sources_1/bd/bpm_mc_bd/ip/bpm_mc_bd_bpm_mc_1_0/bpm_mc_c_addsub_v12_0_i3/bpm_mc_c_addsub_v12_0_i3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bpm_mc_c_addsub_v12_0_i3 || ORIG_REF_NAME==bpm_mc_c_addsub_v12_0_i3} -quiet] -quiet

# IP: /xilinxworks/sysgen/bpm_panda/netlist/ip/bpm_mc/src/ip_catalog/bpm_mc.gen/sources_1/bd/bpm_mc_bd/ip/bpm_mc_bd_bpm_mc_1_0/bpm_mc_div_gen_v5_1_i0/bpm_mc_div_gen_v5_1_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bpm_mc_div_gen_v5_1_i0 || ORIG_REF_NAME==bpm_mc_div_gen_v5_1_i0} -quiet] -quiet

# IP: /xilinxworks/sysgen/bpm_panda/netlist/ip/bpm_mc/src/ip_catalog/bpm_mc.gen/sources_1/bd/bpm_mc_bd/ip/bpm_mc_bd_bpm_mc_1_0/bpm_mc_mult_gen_v12_0_i0/bpm_mc_mult_gen_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bpm_mc_mult_gen_v12_0_i0 || ORIG_REF_NAME==bpm_mc_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: /xilinxworks/sysgen/bpm_panda/netlist/ip/bpm_mc/src/ip_catalog/bpm_mc.gen/sources_1/bd/bpm_mc_bd/ip/bpm_mc_bd_bpm_mc_1_0/constrs/bpm_mc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bpm_mc_bd_bpm_mc_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
